#!/bin/bash

# Exit if any error occurs
set -e

echo "Finishing up the config repo install..."
git submodule init
git submodule update
echo "Done"

echo "Installing vim..."
sudo apt-get -y install vim > /dev/null
echo "Done"

echo "Installing tig first..."
sudo apt-get -y install tig > /dev/null
echo "Done"

echo "Installing zsh..."
sudo apt-get -y install zsh > /dev/null
wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O - | sh > /dev/null
#sudo chsh -s "$(command -v zsh)" "${USER}"
pushd ~/.oh-my-zsh/custom/plugins
git clone git://github.com/zsh-users/zsh-syntax-highlighting.git
popd
echo "Done"

echo "Installing pip..."
sudo apt-get -y install python-pip

echo "Installing powerline status plugin for vim..."
sudo pip install powerline-status
echo "Done"

echo "Setting up fonts for powerline plugin for vim..."
if [ ! -d ~/.fonts ];then
    mkdir ~/.fonts
fi
if [ ! -d ~/.config/fontconfig/conf.d ];then
    mkdir -p ~/.config/fontconfig/conf.d/
fi
cp 10-powerline-symbols.conf ~/.config/fontconfig/conf.d
cp PowerlineSymbols.otf ~/.fonts
echo "Done"

echo "Installing Jedi library for parsing python code..."
sudo pip install jedi
echo "Done"

echo "Lets get pyenv working..."
git clone https://github.com/yyuu/pyenv.git ~/.pyenv > /dev/null
echo "Done"

echo "Installing terminator..."
sudo apt-get -y install terminator
echo "Done"

echo "Copy over the run command files..."
cp zshrc ~/.zshrc
cp vimrc ~/.vimrc
cp -r vim ~/.vim
cp aleks.zsh-theme ~/.oh-my-zsh/themes
echo "Done"

echo "Please close this terminal, and open a new one."
